### ISSUE TITLE
[Suggestion] CONTINUE WORKING ON THIS

### ISSUE THREAD

**Issue by slxdy** [sinai-dev/UniverseLib#1]
This is such a great tool, but as you stated in readme, it's more just for yourself.
IMO you should seriously consider making this tool more user-friendly and make a guide for it.
I can imagine many other people using it (including myself 👀)

**Comment by sinai-dev** [comment]
What would you use it for? At the moment I'm not sure I have the time to properly maintain it, I'm already stretched pretty thin over the projects I manage.

**Comment by slxdy** [comment]
> What would you use it for? 

Own mod menus. I dont feel like making asset bundles

**Comment by sinai-dev** [comment]
Fair enough, well if I get some free time I'll see if I can make it a bit more user friendly, can't guarantee it any time soon though. For now an example to use would be [this](https://github.com/sinai-dev/MelonPreferencesManager/blob/main/src/UI/UIManager.cs), there's a fair bit of unrelated stuff in there but just check out lines 0-50 and then 293 to the end. The value editor things are not actually part of UniverseLib, but you can see some examples of them [here](https://github.com/sinai-dev/MelonPreferencesManager/tree/main/src/UI/InteractiveValues).

**Comment by FungusAmogus** [comment]
@SlidyDev go kill yourself you stupid retarded bitch stop banning me in secret neighbor or i will smash your balls in a blender you fucking faggot you have small cock
