### ISSUE TITLE
Additional Mouse buttons

### ISSUE THREAD

**Issue by SeanLatimer** [sinai-dev/UniverseLib#7]
I was wondering if there is any support planned in the InputManager for additional mouse buttons (2,3,4,5,6 etc) to match the Unity API?

**Comment by sinai-dev** [comment]
I have no control over LegacyInput, we just pass the int argument to `Input.GetMouseButton*`. From what I can see InputSystem supports 0, 1, 2, 3 and 4. I'll add support for 2/3/4 to InputSystem.
